version: "2"
services:
  django:
    container_name: slug_trades
    build:
      context: .
      dockerfile: Dockerfile
    image: slug_trades
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/myproject
    ports:
      - "8000:8000"