# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-07 18:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slug_trade_app', '0002_auto_20180407_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('E', 'Electronics'), ('H', 'Household goods'), ('C', 'Clothing'), ('O', 'Other')], default='O', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('on', 'Located on campus'), ('off', 'Located off campus')], default='on', max_length=3),
        ),
    ]
